[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add custom 404 page
[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
