[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  external_node_modules = ["axios", "ioredis"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src * 'unsafe-inline' 'unsafe-eval'; img-src * data: blob:; connect-src *"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
